title: "Integrative Analysis of Differential Gene Expression, Transcript Usage, and RNA Secondary Structure in Early- and Late-Onset Colorectal Cancer"
author: "Salomon Marquez"
description: "This repository contains the requirements, code, and backlog of my bioinformatics master's thesis developed at CIMA University of Navarra"
theme: minima